package com.auth.ums.enums;

public enum NotificationAction {

    // Authentication & Security
    ACCOUNT_CREATED,
    LOGIN_ALERT,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED,
    PHONE_VERIFIED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,

    // Profile
    PROFILE_UPDATED,
    PROFILE_COMPLETED,
    RESUME_UPLOADED,
    RESUME_UPDATED,
    SKILLS_UPDATED,
    KYC_UPDATED,

    // Job
    JOB_POSTED,
    JOB_UPDATED,
    JOB_EXPIRED,
    JOB_CLOSED,
    JOB_RECOMMENDED,
    JOB_SAVED,

    // Application
    APPLICATION_SUBMITTED,
    APPLICATION_UPDATED,
    APPLICATION_WITHDRAWN,
    APPLICATION_VIEWED,
    APPLICATION_SHORTLISTED,
    APPLICATION_REJECTED,
    APPLICATION_ACCEPTED,

    // Interview
    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CANCELLED,
    INTERVIEW_REMINDER,

    // Employer / Recruiter
    NEW_APPLICANT,
    APPLICATION_RECEIVED,
    CANDIDATE_SHORTLISTED,
    CANDIDATE_HIRED,

    // Communication
    NEW_MESSAGE,
    MESSAGE_REPLY,
    CHAT_RECEIVED,

    // Subscription & Payment
    SUBSCRIPTION_PURCHASED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_EXPIRED,
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED,
    PAYMENT_REFUNDED,
    INVOICE_GENERATED,

    // System
    SYSTEM_ALERT,
    MAINTENANCE_NOTICE,
    FEATURE_ANNOUNCEMENT,

    // Marketing
    PROMOTIONAL,
    NEWSLETTER,

    COMPANY_CREATED, // Generic
    JOB_CREATED, COMPANY_UPDATED, DOCUMENT_UPLOADED, GENERIC_DELETE, GENERIC
}
