export const INDUSTRY_TYPES = [
    'Information Technology (IT)',
    'Software Development',
    'Artificial Intelligence (AI)',
    'Cloud Computing',
    'Cybersecurity',
    'Telecommunications',
    'Banking & Finance',
    'Insurance',
    'Healthcare',
    'Pharmaceuticals',
    'Biotechnology',
    'Education',
    'E-commerce',
    'Retail',
    'Manufacturing',
    'Automotive',
    'Construction',
    'Real Estate',
    'Hospitality',
    'Travel & Tourism',
    'Food & Beverage',
    'Agriculture',
    'Energy',
    'Renewable Energy',
    'Oil & Gas',
    'Logistics & Transportation',
    'Import & Export',
    'Media & Entertainment',
    'Advertising & Marketing',
    'Consulting',
    'Legal Services',
    'Human Resources',
    'Government',
    'Non-Profit Organization',
    'Research & Development',
    'Engineering',
    'Architecture',
    'Fashion & Apparel',
    'Consumer Electronics',
    'Wholesale Distribution',
    'Professional Services',
    'Other',
  ]
  
  export const COMPANY_TYPES = [
    'Private Limited',
    'Public Limited',
    'Partnership',
    'Limited Liability Partnership (LLP)',
    'Sole Proprietorship',
    'Corporation',
    'Startup',
    'Non-Profit Organization',
    'Government Organization',
    'NGO',
    'Cooperative',
    'Joint Venture',
    'Subsidiary',
    'Branch Office',
    'Franchise',
    'Holding Company',
    'Other',
  ]
  
  // value = what gets stored (matches your sample data, e.g. "Medium"); label = what's shown in the dropdown
  export const COMPANY_SIZES = [
    { value: 'Micro', label: 'Micro (1 - 10 employees)' },
    { value: 'Small', label: 'Small (11 - 50 employees)' },
    { value: 'Medium', label: 'Medium (51 - 250 employees)' },
    { value: 'Large', label: 'Large (251 - 1000 employees)' },
    { value: 'Enterprise', label: 'Enterprise (1000+ employees)' },
  ]
  